# Discussion Section Oct 3

## Archive Exploration
1. What is this data about?

This data is for arthropod prey of species in California drylands

2. Is this data collected in-situ by the authors or is it a synthesis of multiple datasets?

Synthesis of multiple datasets

3. During what time frame were the observations in the dataset collected?

Between 1945 and 2022

4. Does this dataset come with an associated metadata file?

Yes!

5. Does the dataset contain sensitive data?

No

## Metadata Explorations

In [2]:
# Import libraries
import pandas as pd

In [4]:
# Access metadata from repository
df = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

In [5]:
df.head()

  attribute                            description
0     class   taxonomic class of observed organism
1     order   taxonomic order of observed organism
2    family  taxonomic family of observed organism
3     genus                             genus name
4   species               full latin binomial name

## Data Loading

In [6]:
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744')

In [7]:
# What is the type of the prey variable?
type(prey)

pandas.core.frame.DataFrame

In [8]:
# Prey is a dataframe

In [9]:
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [10]:
# There are 40 columns. Many of the columns are not very descriptive (bio4, bio5, etc.). There is also a column with camel case

In [13]:
pd.set_option("display.max.columns", None)
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [14]:
# `pd.set_option("display.max.columns", None)` allows you to see all 40 of the column names instead of just the first and last 10

## pd.DataFrame Preliminary Exploration

In [21]:
# `head()` shows the first 5 rows of the dataframe
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

In [23]:
# `tail()` shows the last 5 rows of the dataframe
prey.tail()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
111151,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,33.660853,-115.721380,1980-04-10T00:00:00Z,10.0,4.0,1980,MCZ,3036.0,PRESERVED_SPECIMEN,1.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111152,200.539291,297.044373,111.539291,131.447403,21.313471,0.464611,50.358723,45.637127,7.404018,33.626942,44.287857,158.105041,43.560184,7319.267090,393.674744,34.807846,358.866913,217.827911,227.579758,0.925702,548.778870,barren,1187.127441
111152,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,35.933333,-116.716667,1998-03-26T00:00:00Z,26.0,3.0,1998,MCZ,NaN,PRESERVED_SPECIMEN,2.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111153,230.166946,344.166931,117.216942,49.012608,8.380343,1.000000,50.700531,21.778294,4.391233,9.430344,19.810688,163.872391,39.000000,8878.634766,442.558167,26.608175,415.950012,141.977646,273.793304,7.429875,-13.553053,grassland,792.632141
111153,Insecta,Hymenoptera,Formicidae,Liometopum,Liometopum occidentale,34.156833,-118.726833,2010-05-21T00:00:00Z,21.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,40.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111154,161.271088,216.747421,116.372208,499.779816,106.116470,0.000000,96.797958,289.033630,4.470360,11.920360,279.654663,128.898209,53.252625,3962.391846,291.092560,51.291302,239.801269,118.917351,209.822205,2.387915,347.122986,grassland,4219.497559
111154,Insecta,Hymenoptera,Formicidae,Pogonomyrmex,Pogonomyrmex californicus,32.989167,-116.658500,2010-05-25T00:00:00Z,25.0,5.0,2010,MCZ,NaN,PRESERVED_SPECIMEN,30.0,4bfac3ea-8763-4f4b-a71a-76a6f5f243d3,111155,140.342300,217.269943,76.576256,559.577881,102.406273,3.000000,78.449997,293.045471,25.936378,36.503853,270.567810,154.063629,49.683960,5537.141602,315.901031,8.395161,307.505859,83.576256,199.928528,6.917791,981.674377,grassland,4865.626465
111155,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,36.251400,-117.731400,1992-09-02T00:00:00Z,2.0,9.0,1992,NTNU-VM,100000.0,PRESERVED_SPECIMEN,1.0,1bec5de3-758c-4ed2-ab13-1597601ad07a,111156,102.202797,197.274719,18.412592,294.105835,48.132629,6.007638,59.663151,133.747376,27.179491,31.660290,133.747376,141.080276,41.000000,7069.728027,293.179962,-47.896355,341.076324,20.241280,171.378082,23.553705,1913.307861,grassland,1628.940918

In [22]:
# `info()` shows the column names, number of non null values and the type of column
prey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111156 entries, 0 to 111155
Data columns (total 40 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   class                          111156 non-null  object
 1   order                          111054 non-null  object
 2   family                         111156 non-null  object
 3   genus                          111156 non-null  object
 4   species                        111156 non-null  object
 5   lat                            111156 non-null  float64
 6   long                           111156 non-null  float64
 7   eventDate                      111156 non-null  object
 8   day                            110998 non-null  float64
 9   month                          111127 non-null  float64
 10  year                           111156 non-null  int64
 11  institutionCode                110414 non-null  object
 12  coordinateUncertaintyInMeters  84686 non-null   float64
 13  basisOfRecord                  111156 non-null  object
 14  individualCount                6351 non-null    float64
 15  datasetKey                     111156 non-null  object
 16  ID                             111156 non-null  int64
 17  bio1                           109629 non-null  float64
 18  bio10                          109629 non-null  float64
 19  bio11                          109629 non-null  float64
 20  bio12                          109629 non-null  float64
 21  bio13                          109629 non-null  float64
 22  bio14                          109629 non-null  float64
 23  bio15                          109629 non-null  float64
 24  bio16                          109629 non-null  float64
 25  bio17                          109629 non-null  float64
 26  bio18                          109629 non-null  float64
 27  bio19                          109629 non-null  float64
 28  bio2                           109629 non-null  float64
 29  bio3                           109629 non-null  float64
 30  bio4                           109629 non-null  float64
 31  bio5                           109629 non-null  float64
 32  bio6                           109629 non-null  float64
 33  bio7                           109629 non-null  float64
 34  bio8                           109629 non-null  float64
 35  bio9                           109629 non-null  float64
 36  dist                           109500 non-null  float64
 37  dem90_hf                       107765 non-null  float64
 38  lc_class                       106905 non-null  object
 39  ndvi                           109663 non-null  float64
dtypes: float64(28), int64(2), object(10)
memory usage: 33.9+ MB

In [24]:
# `nunique()` shows the count of unique observations for each column
prey.nunique()

class                                 4
order                                18
family                               63
genus                                92
species                              97
lat                               91909
long                              91965
eventDate                        102140
day                                  31
month                                12
year                                 77
institutionCode                      77
coordinateUncertaintyInMeters      4450
basisOfRecord                         4
individualCount                      42
datasetKey                           88
ID                               111156
bio1                              11778
bio10                             11981
bio11                             11803
bio12                             12117
bio13                             12020
bio14                              4586
bio15                             11848
bio16                             12102
bio17                              9243
bio18                             10698
bio19                             12095
bio2                              11915
bio3                               8723
bio4                              12110
bio5                              11992
bio6                              11934
bio7                              12088
bio8                              11889
bio9                              11980
dist                              11718
dem90_hf                          11904
lc_class                             12
ndvi                              29093
dtype: int64

In [25]:
# Change the default value of head()
prey.head(10)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
5,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,37.842187,-122.272478,2020-05-02T10:28:25Z,2.0,5.0,2020,iNaturalist,917.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,6,144.511795,178.412857,105.581818,565.076050,122.171043,1.000000,87.983589,308.378662,7.063087,9.205670,308.378662,89.164856,51.079494,2885.461670,234.265152,60.451580,173.813568,105.581818,172.760529,0.365533,35.971046,urban,3031.351807
6,Insecta,Orthoptera,Acrididae,Schistocerca,Schistocerca nitens,33.854472,-117.817876,2022-07-24T19:59:00Z,24.0,7.0,2022,iNaturalist,160.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,7,177.032990,228.031799,132.172546,338.124573,72.213455,0.995521,89.869400,195.220841,6.873608,13.652244,183.396042,135.359924,55.000000,3758.806885,303.441711,60.240211,243.201508,136.165970,221.020721,0.705537,105.866028,urban,2929.991455
7,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,33.750705,-116.743667,2022-10-15T14:03:29Z,15.0,10.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,8,120.158730,199.906616,53.729237,616.566406,105.341469,3.252115,72.506027,306.442810,35.863651,60.013138,296.442810,157.927048,49.197884,5878.874512,302.063477,-16.578903,318.642364,58.158726,172.410843,1.145492,1639.430786,grassland,5714.669922
8,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,33.235500,-117.280700,2016-12-13T08:00:00Z,13.0,12.0,2016,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,9,168.944000,217.027542,127.524216,302.635620,59.679543,1.225997,86.732315,166.990814,6.451993,12.225997,155.940826,115.709236,53.982101,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
9,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.323517,-122.174308,2019-04-29T15:22:16Z,29.0,4.0,2019,iNaturalist,5.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,10,131.805481,181.386352,89.509621,824.623535,164.044968,2.000000,86.375435,431.711121,11.555281,15.646415,431.711121,118.941368,54.445618,3672.007080,252.594223,35.436752,217.157471,89.509621,176.914505,1.444703,532.485596,evergreen_needleleaf,7056.129395

In [33]:
# `shape` shows the number of rows and columns
prey.shape

(111156, 40)

In [34]:
# `columns` shows the different names of all the columns
prey.columns

Index(['class', 'order', 'family', 'genus', 'species', 'lat', 'long',
       'eventDate', 'day', 'month', 'year', 'institutionCode',
       'coordinateUncertaintyInMeters', 'basisOfRecord', 'individualCount',
       'datasetKey', 'ID', 'bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14',
       'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio3', 'bio4',
       'bio5', 'bio6', 'bio7', 'bio8', 'bio9', 'dist', 'dem90_hf', 'lc_class',
       'ndvi'],
      dtype='object')

In [35]:
# `dtypes` shows the type of variables in each column (object, float, int...)
prey.dtypes

class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object

## Update column names

In [39]:
# Change the column names of institutionCode and datasetKey to institution_code and dataset_key
prey = prey.rename(columns = {'institutionCode' : 'institution_code', 'datasetKey' : 'dataset_key'})

# Confirm columns are renamed
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104